---
- name: Onboard big-ip
  hosts: bigip1a
  gather_facts: false
  connection: local
  vars:
    provider:
      server: "{{ inventory_hostname }}.f5trn.com"
      user: "{{ admin_user }}"
      password: "{{ admin_default_password }}"
      validate_certs: false

  tasks:
  - name: Set timezone and NTP serverr
    bigip_device_ntp:
      timezone: America/Los_Angeles
      ntp_servers: 
      - pool.ntp.org
      provider: "{{ provider }}"
  - name: set hostname
    bigip_hostname:
      hostname: "{{ inventory_hostname }}.f5trn.com"
      provider: "{{ provider }}"
  - name: set DNS
    bigip_device_dns:
      name_servers:
      - 10.10.1.2 
      search:
      - f5trn.com
      provider: "{{ provider }}"

