---
- name: Play 1 - List the hosts in the inventory file 
  hosts: bigips
  gather_facts: false
  tasks:
  - name: Task 1 - print hostname (repeat for each host)
    debug:
      msg: "{{ inventory_hostname }} - Host"
  - name: Task 2 - ping every host
    ping:

